# Generated by Django 3.2.5 on 2022-02-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220204_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Dish',
            new_name='disha',
        ),
    ]
