# Generated by Django 3.2.5 on 2022-02-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_dish_user_disha'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
