# Generated by Django 3.2.5 on 2022-02-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avater',
            new_name='avatar',
        ),
    ]
