# Generated by Django 3.2.5 on 2022-02-05 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_creator_developer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='behance',
            new_name='disha',
        ),
        migrations.RenameField(
            model_name='creator',
            old_name='dribble',
            new_name='meduim',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='disha',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='meduim',
            new_name='gitlab',
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dribble', models.CharField(blank=True, max_length=300, null=True)),
                ('behance', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
