# Generated by Django 3.2.5 on 2022-02-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220205_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
