# Generated by Django 3.2.5 on 2022-02-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
