# Generated by Django 3.2.5 on 2022-02-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_message_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='status',
            new_name='helpful',
        ),
        migrations.AddField(
            model_name='message',
            name='not_helpful',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
