# Generated by Django 3.2.5 on 2022-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20220211_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='helpful',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='not_helpful',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
