# Generated by Django 3.2.5 on 2022-02-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20220211_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='helpful',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='not_helpful',
            field=models.IntegerField(default=0),
        ),
    ]
